### ISSUE TITLE
Try to run

### ISSUE THREAD

**Issue by retraut** [Dica-Developer/ingress-cluster#1]
Try to run your app. But have a blank screen.
Where I can find 
/dist/main.css 
/dist/bundle.js

**Comment by JayGray** [comment]
First of all. Please be aware this a 'pre alpha initial commit bla bla'  thingy ;) .
Thats why nothing is documented yet.
All portals for now are hard coded and from our home town only.
If you really want to try please run following commands.
You will need at least two open shells.
`npm run hot-dev-server` and `npm run start-hot` should blow up the app in dev mode.

Cheers

**Comment by mschaaf** [comment]
I guess I need to call npm install before. Also you need v0.12.x as a minimum.
I had errors about missing modules after the first command.
Following modules where missed: to-fast-properties, esutils, repeating, globals, line-numbers, js-tokens, chalk, babylon, convert-source-map, minimatch, slash, path-exists, json5, path-is-absolute, shebang-regex, ...

**Comment by mschaaf** [comment]
The second command fails with: sh: electron: command not found
What is missing?

**Comment by JayGray** [comment]
You need to have at least `electron-prebuilt` installed globally.
https://github.com/atom/electron

**Comment by mschaaf** [comment]
Ok installed it right now. Now the app starts but fails with an error of a missing module.
module name: regexpu/rewrite-pattern

The installation `npm install regexpu/rewrite-pattern` fails with: `Repository not found`.
